//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasuvis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionID { get; set; }
        public string ServiceID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
